// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5nwUZczXlCvA_h6KCsQCcJf9tZNsIoMM',
    appId: '1:583394854357:web:69110d0a135d763926e95c',
    messagingSenderId: '583394854357',
    projectId: 'kxng-first-flutter-app',
    authDomain: 'kxng-first-flutter-app.firebaseapp.com',
    storageBucket: 'kxng-first-flutter-app.firebasestorage.app',
    measurementId: 'G-W316F0PG83',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjceAovyWloR8KlTTkM76qqs60UGmtvug',
    appId: '1:583394854357:android:7316a4b5bbafd57926e95c',
    messagingSenderId: '583394854357',
    projectId: 'kxng-first-flutter-app',
    storageBucket: 'kxng-first-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClgQekwit5h5JuiBx8CHh59J802i20_70',
    appId: '1:583394854357:ios:e279dd4a5b1f4c6726e95c',
    messagingSenderId: '583394854357',
    projectId: 'kxng-first-flutter-app',
    storageBucket: 'kxng-first-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.bookshelf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClgQekwit5h5JuiBx8CHh59J802i20_70',
    appId: '1:583394854357:ios:e279dd4a5b1f4c6726e95c',
    messagingSenderId: '583394854357',
    projectId: 'kxng-first-flutter-app',
    storageBucket: 'kxng-first-flutter-app.firebasestorage.app',
    iosBundleId: 'com.example.bookshelf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5nwUZczXlCvA_h6KCsQCcJf9tZNsIoMM',
    appId: '1:583394854357:web:18cfbc89cad1d3cc26e95c',
    messagingSenderId: '583394854357',
    projectId: 'kxng-first-flutter-app',
    authDomain: 'kxng-first-flutter-app.firebaseapp.com',
    storageBucket: 'kxng-first-flutter-app.firebasestorage.app',
    measurementId: 'G-7L8JGSV0Z4',
  );
}
